=== jagraves21/jagraves21.github.io/grants/grants.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<!-- targetNamespace="https://sghafoor10.github.io" -->
	<!-- xmlns="https://sghafoor10.github.io" -->

	<xs:element name="GRANTS" type="GrantCatalog"/>
	
	<xs:complexType name="GrantCatalog">
		<xs:sequence>
			<xs:element name="GRANT" type="GrantType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="GrantType">
		<xs:sequence>
			<xs:element name="TITLE" type="NoteType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="AGENCY" type="NoteType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="START_DATE" type="DateType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="END_DATE" type="DateType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="AMOUNT" type="PhaseType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="LEAD_PI" type="NoteType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="TTU_PI" type="NoteType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="PI" type="NoteType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="CO_PI" type="NoteType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SENIOR_PERSONNEL" type="NoteType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="NOTE" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="NoteType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="note" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="DateType">
		<xs:simpleContent>
			<xs:extension base="GrantDate">
				<xs:attribute name="note" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="GrantDate">
		<xs:union memberTypes="xs:date xs:gYearMonth xs:gYear"/>
	</xs:simpleType>

	<xs:complexType name="PhaseType">
		<xs:complexContent>
			<xs:extension base="NoteType">
				<xs:attribute name="phase" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== jagraves21/jagraves21.github.io/grants/grants.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="grants.xsl"?>

<GRANTS 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://sghafoor10.github.io/grants grants.xsd">
	<!-- xmlns="https://sghafoor10.github.io" -->
	
	<GRANT>
		<TITLE>Lake Observations from Citizen Scientists and Satellites: Validation of Satellite Altimetry to Support Hydrologic Science</TITLE>
		<AGENCY>National Science Foundation (NSF)</AGENCY>
		<START_DATE>2021-06-24</START_DATE>
		<END_DATE>2025-12-31</END_DATE>
		<AMOUNT phase="Prototype" note="TTU Portion: $65,071">$359,886</AMOUNT>
		<AMOUNT phase="Implementation" note="TTU Portion: $247,275">$1,200,000</AMOUNT>
		<LEAD_PI>Tamlin Pavelsky</LEAD_PI>
		<TTU_PI>Sheikh Ghafoor</TTU_PI>
		<CO_PI>Grant Parkins</CO_PI>
		<CO_PI>Faisal Hossain</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Collaborative Research: CyberTraining: Implementation: Medium: Broadening Adoption of Parallel and Distributed Computing in Undergraduate Computer Science and Engineering Curricula</TITLE>
		<AGENCY>National Science Foundation (NSF)</AGENCY>
		<START_DATE>2020-10-15</START_DATE>
		<END_DATE>2023-10-14</END_DATE>
		<AMOUNT note="TTU Portion: $64,220">$1,000,000</AMOUNT>
		<LEAD_PI>Sushil Prasad</LEAD_PI>
		<TTU_PI>Sheikh Ghafoor</TTU_PI>
		<CO_PI>Charles Weems</CO_PI>
		<CO_PI>Ramachandran Vaidyanathan</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>XiveNet: An Extensible, Innovative, and Open Architecture Testbed for In-Vehicle Network Security Research</TITLE>
		<AGENCY>National Security Agency (NSA)</AGENCY>
		<START_DATE>2020-09-01</START_DATE>
		<END_DATE>2022-08-31</END_DATE>
		<AMOUNT>$299,992</AMOUNT>
		<LEAD_PI>Sheikh Ghafoor</LEAD_PI>
		<CO_PI>Ambareen Siraj</CO_PI>
		<CO_PI>Stacy Prowell</CO_PI>
		<CO_PI>Anthony Skjellum</CO_PI>
		<CO_PI>Farah Kandah</CO_PI>
		<CO_PI>Mark Yampolskiy</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Collaborative Research: SaTC: EDU: Artificial Intelligence Assisted Malware Analysis</TITLE>
		<AGENCY>National Security Agency (NSA)</AGENCY>
		<START_DATE>2020-08-01</START_DATE>
		<END_DATE>2023-07-31</END_DATE>
		<AMOUNT note="TTU Portion: $183,263">$400,000</AMOUNT>
		<LEAD_PI>Maanak Gupta</LEAD_PI>
		<CO_PI>Sheikh Ghafoor</CO_PI>
		<CO_PI>Sudip Mittal</CO_PI>
		<CO_PI>Mahmoud Abdelsalam</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>CC* CRIA: Planning a Regional Cyber-Infrastructure-Research Consortium for Middle Tennessee</TITLE>
		<AGENCY>National Security Agency (NSA)</AGENCY>
		<START_DATE>2020-07-01</START_DATE>
		<END_DATE>2021-12-31</END_DATE>
		<AMOUNT note="TTU Portion: $82,220">$249,713</AMOUNT>
		<LEAD_PI>Anthony Skjellum</LEAD_PI>
		<TTU_PI>Sheikh Ghafoor</TTU_PI>
		<CO_PI>Gerald Gannod</CO_PI>
		<CO_PI>Ryan Otter</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Software Engineering Workforce Development in High Performance Computing for Digital Twins</TITLE>
		<AGENCY>National Science Foundation (NSF)</AGENCY>
		<START_DATE>2019-10-01</START_DATE>
		<END_DATE>2020-09-30</END_DATE>
		<AMOUNT note="TTU Portion: $42,000">$100,000</AMOUNT>
		<LEAD_PI>Anthony Skjellum</LEAD_PI>
		<CO_PI>Sheikh Ghafoor</CO_PI>
		<CO_PI>Gerald Gannod</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Adaptive and Reconfigurable Sensor Elements and Networks for Monitoring Critical Infrastructure and Maneuver Corridors</TITLE>
		<AGENCY>Research and Development Center (ERDC), US Army Corps of Engineers Engineers (USACE)</AGENCY>
		<START_DATE>2019-09-25</START_DATE>
		<END_DATE>2020-09-24</END_DATE>
		<AMOUNT>$957,444.48</AMOUNT>
		<PI>Charles Van Neste</PI>
		<CO_PI>Sheikh Ghafoor</CO_PI>
		<CO_PI>Satish Mahajan</CO_PI>
		<CO_PI>Jeff Austen</CO_PI>
		<CO_PI>Michael Rogers</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>From Can’t to CAN: Attack Prevention &amp; In-Situ Detection of Advanced Attacks on Controller Area Networks</TITLE>
		<AGENCY>Oak Ridge National Laboratory (ORNL)</AGENCY>
		<START_DATE>2019-03-11</START_DATE>
		<END_DATE>2020-09-30</END_DATE>
		<AMOUNT>$56,260</AMOUNT>
		<PI>Sheikh Ghafoor</PI>
	</GRANT>
	<GRANT>
		<TITLE>Semi-Automatic Assessment of Parallel Programs in Training of Students and Faculty</TITLE>
		<AGENCY>National Science Foundation (NSF)</AGENCY>
		<START_DATE>2019-09-01</START_DATE>
		<END_DATE>2021-08-31</END_DATE>
		<AMOUNT note="TTU Portion: $82,000">$200,000</AMOUNT>
		<LEAD_PI>Prasun Dewan</LEAD_PI>
		<TTU_PI>Sheikh Ghafoor</TTU_PI>
	</GRANT>
	<GRANT>
		<TITLE>Detection and Analysis of Malware in Critical Infrastructure</TITLE>
		<AGENCY>Oak Ridge National Laboratory (ORNL)</AGENCY>
		<START_DATE>2018-10-01</START_DATE>
		<END_DATE>2020-09-30</END_DATE>
		<AMOUNT>$336,000</AMOUNT>
		<PI>Sheikh Ghafoor</PI>
		<CO_PI>Michael Rogers</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Black Box: Highly Secure Environment for Health Data Computation</TITLE>
		<AGENCY>Oak Ridge National Laboratory (ORNL)</AGENCY>
		<START_DATE>2018-08-01</START_DATE>
		<END_DATE>2021-09-30</END_DATE>
		<AMOUNT>$112,508</AMOUNT>
		<PI>Sheikh Ghafoor</PI>
		<CO_PI>Michael Rogers</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Development and Improvement of High-Resolution Flood-2D GPU Modeling Titan HPC Environment</TITLE>
		<AGENCY>Oak Ridge National Laboratory (ORNL)</AGENCY>
		<START_DATE>2018-08-01</START_DATE>
		<END_DATE>2019-07-31</END_DATE>
		<AMOUNT>$296,192</AMOUNT>
		<PI>Alfred Kalyanapu</PI>
		<CO_PI>Sheikh Ghafoor</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Cyber Training: CDL: iPDC – Summer Institute for Integrating Parallel and Distributed Computing in Introductory Programming Classes</TITLE>
		<AGENCY>National Science Foundation (NSF)</AGENCY>
		<START_DATE>2017-09-01</START_DATE>
		<END_DATE>2020-08-31</END_DATE>
		<AMOUNT>$499,988</AMOUNT>
		<PI>Sheikh Ghafoor</PI>
		<CO_PI>Michael Rogers</CO_PI>
		<CO_PI>David Brown</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Tracking Water Storage in Lakes: Citizens and Satellites</TITLE>
		<AGENCY>National Aeronautics and Space Administration (NASA)</AGENCY>
		<START_DATE>2017-01</START_DATE>
		<END_DATE>2022-06</END_DATE>
		<AMOUNT phase="Prototype" note="TTU Portion: $31,898">$152,674</AMOUNT>
		<AMOUNT phase="Implementation" note="TTU Portion: $255,000">$1,492,802</AMOUNT>
		<LEAD_PI>Tamlin Pavelsky</LEAD_PI>
		<TTU_PI>Sheikh Ghafoor</TTU_PI>
		<CO_PI>Grant Parkins</CO_PI>
		<CO_PI>Faisal Hossain</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Benchmark and Analyze of Open Source Parallel XXT Libraries on Different HPC Architectures for Performance Prediction</TITLE>
		<AGENCY>Oak Ridge National Laboratory (ORNL)</AGENCY>
		<START_DATE>2016-11-11</START_DATE>
		<END_DATE>2017-09-30</END_DATE>
		<AMOUNT>$25,000</AMOUNT>
		<PI>Sheikh Ghafoor</PI>
	</GRANT>
	<GRANT>
		<TITLE>Develop and Benchmark Architecture Agnostic Scalable Library of Data Parallel Kernels for Big Data Architecture</TITLE>
		<AGENCY>Oak Ridge National Laboratory (ORNL)</AGENCY>
		<START_DATE>2016-04-01</START_DATE>
		<END_DATE>2016-09-30</END_DATE>
		<AMOUNT>$25,000</AMOUNT>
		<PI>Sheikh Ghafoor</PI>
	</GRANT>
	<GRANT>
		<TITLE>Development of Integrated DHSVM-Flood2D-GPU Modeling Framework for Regional-Scale Modeling of High-Resolution Rapid Flood Risk Assessment</TITLE>
		<AGENCY>Oak Ridge National Laboratory (ORNL)</AGENCY>
		<START_DATE>2016-03-01</START_DATE>
		<END_DATE>2016-09-30</END_DATE>
		<AMOUNT>$60,000</AMOUNT>
		<PI>Alfred Kalyanapu</PI>
		<CO_PI>Sheikh Ghafoor</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Knowledge-Based Flood Inundation Forecast on Affordable Mobile Platforms to Empower Farmers</TITLE>
		<AGENCY>University of Washington</AGENCY>
		<START_DATE>2015-10</START_DATE>
		<END_DATE>2017-09</END_DATE>
		<AMOUNT note="TTU Portion: $35,000">$150,000</AMOUNT>
		<LEAD_PI>Faisal Hossain</LEAD_PI>
		<TTU_PI>Sheikh Ghafoor</TTU_PI>
	</GRANT>
	<GRANT>
		<TITLE>iPDC: Integrating Parallel and Distributed Computing in Introductory Programming</TITLE>
		<AGENCY>National Science Foundation (NSF)</AGENCY>
		<START_DATE>2015-08</START_DATE>
		<END_DATE>2016-07</END_DATE>
		<AMOUNT>$49,973</AMOUNT>
		<PI>Sheikh Ghafoor</PI>
		<CO_PI>Michael Rogers</CO_PI>
	</GRANT>
	<GRANT>
		<TITLE>Integrating Hands on Security Exercises in Computer Networks Class</TITLE>
		<AGENCY>Intel-NSF-GTISC Security Education Micro-grant Program</AGENCY>
		<START_DATE>2015-01</START_DATE>
		<END_DATE>2015-12</END_DATE>
		<AMOUNT>$5,000</AMOUNT>
		<PI>Sheikh Ghafoor</PI>
	</GRANT>
	<GRANT>
		<TITLE>Collaborative Research: CyberWorkshops: Resources and Strategies for Teaching Cybersecurity in Computer Science (CReST)</TITLE>
		<AGENCY>National Science Foundation (NSF)</AGENCY>
		<START_DATE>2014-09</START_DATE>
		<END_DATE>2017-08</END_DATE>
		<AMOUNT>$422,917</AMOUNT>
		<PI>Ambareen Siraj</PI>
		<CO_PI>Sheikh Ghafoor</CO_PI>
	</GRANT>
	<!--<GRANT>
		<TITLE>Department Wide Parallel and Distributed Computing Adoption</TITLE>
		<AGENCY>National Science Foundation (NSF) TCPP Early Adopter</AGENCY>
		<AMOUNT>$5,500</AMOUNT>
		<PI>Sheikh Ghafoor</PI>
		<CO_PI>Michael Rogers</CO_PI>
	</GRANT>-->
	<GRANT>
		<TITLE>SecKnitKit (Security Knitting Kit): Integrating Security into Traditional Computer Science Courses</TITLE>
		<AGENCY>National Science Foundation (NSF)</AGENCY>
		<START_DATE>2012-08-15</START_DATE>
		<END_DATE>2014-07-31</END_DATE>
		<AMOUNT>$199,872</AMOUNT>
		<PI>Ambareen Siraj</PI>
		<CO_PI>Sheikh Ghafoor</CO_PI>
	</GRANT>
	<!--<GRANT>
		<TITLE>Collaborative Research: CyberTraining: Conceptualization: Planning a Sustainable Ecosystem for Incorporating Parallel and Distributed Computing into Undergraduate Education</TITLE>
		<AGENCY>National Science Foundation (NSF)</AGENCY>
		<START_DATE>2019-11-21</START_DATE>
		<AMOUNT>$423,921</AMOUNT>
		<PI>Sushil Prasad</PI>
		<SENIOR_PERSONNEL>Sheikh Ghafoor</SENIOR_PERSONNEL>
	</GRANT>-->
	<GRANT>
		<TITLE>Autonomic Dynamic Resource-­Aware Runtime System</TITLE>
		<AGENCY>Sandia National Laboratories (SNL)</AGENCY>
		<START_DATE>2011-01</START_DATE>
		<END_DATE>2011-09</END_DATE>
		<AMOUNT>$75,000</AMOUNT>
		<PI>Stephen Scott</PI>
		<SENIOR_PERSONNEL>Sheikh Ghafoor</SENIOR_PERSONNEL>
	</GRANT>
	<GRANT>
